export const ADMIN_ROUTE = '/admin'
export const LOGIN_ROUTE = '/login'
export const LESSON_ROUTE = '/lesson'
export const MAIN_ROUTE = '/'
export const MATERIAL_ROUTE = '/material'
export const RESTORE_ROUTE = '/restore'
export const USER_ROUTE = '/user'